// src/views/Status.vue
<script lang="ts">
import axios from "axios";
export default {
    data() {
        return {
            loading: true,
            status: "",
            herokuStatus: {},
            discordStatus: {},
            errors: [],
            uptime: "",
        };
    },
    created() {
        axios
            .get("https://potato-bot-api.up.railway.app/status")
            .then((response) => {
                this.status = response.data.message ? "Online" : "Offline";
                this.errors = response.data.errors;
                let ms_num = response.data.uptime;
                let days = Math.floor(ms_num / (1000 * 60 * 60 * 24));
                let hours = Math.floor((ms_num / 1000 / 60 / 60) % 24);
                let minutes = Math.floor((ms_num / 1000 / 60) % 60);
                this.uptime = `${days} days, ${hours} hours, ${minutes} minutes`;
                this.loading = false;
            })
            .catch((error) => {
                console.error(error);
            });
        axios
            .get("https://status.heroku.com/api/v4/current-status")
            .then((response) => {
                this.herokuStatus = response.data;
                this.loading = false;
            });
        axios
            .get("https://discordstatus.com/api/v2/summary.json")
            .then((response) => {
                this.discordStatus = response.data;
                this.loading = false;
            })
            .catch((error) => {
                console.error(error);
            });
        setTimeout(() => {
            console.log("e");
            this.$forceUpdate();
        }, 10000);
    },
};
</script>

<template>
    <div id="status">
        <h1 class="text-5xl">Status</h1>
        <p>
            Status:
            <span v-if="!loading"><span v-if="!status"><a href="https://potato-bot-api.up.railway.app/status">Our
                        API</a>
                    haven't responded yet, most likely because heroku is down (check the
                    heroku incidents below)</span><span v-else>{{ status }}</span></span><span
                v-else>Loading...</span><br />
            Heroku Status: <span v-if="loading">Loading...<br /></span>
            <span v-else>
                <li v-for="status in herokuStatus.status" :key="status.system">
                    {{ status.system }}: {{ status.status }}
                </li>
                Incidents:
                <ul>
                    <li v-for="incident in herokuStatus.incidents" :key="incident.id">
                        <a :href="`https://status.heroku.com/incidents/${incident.id}`" target="_blank">{{
                                incident.title
                        }}</a>
                    </li>
                </ul>
                <br />
            </span>
            Uptime:
            <span v-if="!loading"><span v-if="!status"><a href="https://potato-bot-api.up.railway.app/status">Our
                        API</a>
                    haven't responded yet, most likely because heroku is down (check the
                    heroku incidents above)</span><span v-else>{{ status }} for {{ uptime }}</span></span><span
                v-else>Loading...</span>
        </p>
        <h3 class="text-3xl">Latest Errors</h3>
        <ul>
            <li v-if="loading">Loading...</li>
            <div v-else>
                <li v-for="(error) in errors" :key="error.id">
                    <a :href="`/status/${error.id}`"><span>{{ error.id.slice(0, 4) }}...</span> -
                        <strong>{{ error.error }}</strong></a>
                </li>
                <p v-if="errors.length === 0">No Errors, yay!</p>
            </div>
        </ul>
    </div>
</template>

// routes/status.tsx
/** @jsx h */
import { h } from "preact";
import { tw } from "@twind";
import TopNav from "../islands/TopNav.tsx";
import { apiStuff } from "../static/apistuff.ts"
import { Handlers, PageProps } from "$fresh/server.ts";
const { errors, uptime, online } = apiStuff;

export const handler: Handlers = {
    async GET(_req, ctx) {
        const discordStatusResponse = await fetch("https://discordstatus.com/api/v2/summary.json");
        const herokuStatusResponse = await fetch("https://status.heroku.com/api/v4/current-status");
        const discordStatus = discordStatusResponse.status == 200 ? await discordStatusResponse.json() : "Error while fetching status from discord";
        const herokuStatus = herokuStatusResponse.status == 200 ? await herokuStatusResponse.json() : "Error while fetching status from heroku";
        return ctx.render({ discordStatus, herokuStatus });
    },
};

export default function Status(props: PageProps) {
    const status = online ? "Online" : "Offline";
    const ms_num = uptime;
    const days = Math.floor(ms_num / (1000 * 60 * 60 * 24));
    const hours = Math.floor((ms_num / 1000 / 60 / 60) % 24);
    const minutes = Math.floor((ms_num / 1000 / 60) % 60);
    const uptimeFormatted = `${days} days, ${hours} hours, ${minutes} minutes`;
    console.log({ uptime, uptimeFormatted, days, hours, minutes });
    return (
        <div class={tw`bg-background h-screen`}>
            <TopNav /><br /><br /><br />
            <main>
                <h1 class={tw`text-5xl pb-3`}>Status</h1>
                <p>Status: {status}</p>
                <p>Uptime: {status} for {uptimeFormatted}</p>
                <p>Heroku Status: {props.data.herokuStatus instanceof String ? props.data.herokuStatus : props.data.herokuStatus.status.map((status: { system: string, status: string }) => {
                    return (<li>
                        {status.system}: {status.status}
                    </li>)
                })}Incidents: <ul>
                        {
                            props.data.herokuStatus.incidents.map((incident: { id: string, title: string }) => {
                                return (<li>
                                    <a href={`https://status.heroku.com/incidents/${incident.id}`} target="_blank">{incident.title}</a>
                                </li>)
                            })
                        }
                    </ul>
                </p>
                <h3 class={tw`text-3xl`}>Latest Errors</h3>
                <ul>
                    <div>
                        {errors.map((error) => {
                            return (
                                <li>
                                    <a href={`/error/${error.id}`}><span>{error.id.slice(0, 4)}...</span> -
                                        <strong>{error.error}</strong></a>
                                </li>
                            )
                        })}
                        {errors.length === 0 ? <p> No Errors, yay! </p> : null}
                    </div>
                </ul>
            </main>
        </div >
    );
}
